name: "🐞 Bug 报告"
description: 给 Modern.js 报告 bug
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间报告这个问题！
  - type: textarea
    id: versions
    attributes:
      label: 版本信息
      description: 在命令行执行 `npm ls @modern-js/app-tools` 的输出。
      render: sh
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 问题详情
      description: 请清晰地描述您遇到的问题。（可包括截图等内容。）
    validations:
      required: true
  - type: input
    id: repro
    attributes:
      label: 问题复现
      description: "请提供一个精炼的问题复现（去除无关依赖的最小化可运行 demo）。 请在下方贴入在 CodePen 上 demo 的链接（[<kbd>⌘</kbd>+点击这里打开模板](https://codepen.io/Justineo/pen/yLbxxOR)）或者复现项目的 repo 地址："
    validations:
      required: true
