name: "✨ 新功能建议"
description: 给 Modern.js 提交新功能建议
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间报告这个问题！
  - type: textarea
    id: details
    attributes:
      label: 新功能详情
      description: 请清晰地描述此功能的适用场景，以及可能的相关 API 的设想。
    validations:
      required: true
